server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://${ip}:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
ip: localhost


